# Generated by Django 2.2.9 on 2023-01-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20230103_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestform',
            old_name='p0ll_title',
            new_name='poll_title',
        ),
    ]
