# Generated by Django 2.2.9 on 2023-01-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20230103_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='candidates_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Candidate's name"),
        ),
    ]
